<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>puppy_slam</name>
  <version>0.0.1</version>
  <description>SLAM configurations for Puppy robot</description>
  <maintainer email="veni@todo.todo">veni</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>slam_toolbox</depend>
  <depend>cartographer_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
