<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>puppy_bringup_cpp</name>
  <version>0.0.0</version>
  <description>C++ implementation of puppy_bringup ROS2 nodes.</description>
  <maintainer email="veni@todo.todo">veni</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>tf2_ros</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>rosgraph_msgs</depend>
  <depend>builtin_interfaces</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>puppy_core_cpp</exec_depend>
  <exec_depend>puppypi_adapter_cpp</exec_depend>
  <exec_depend>puppy_gait_cpp</exec_depend>
  <exec_depend>puppy_nav_cpp</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
